### ISSUE TITLE
Creating default object from empty value when updating event

### ISSUE THREAD

**Issue by Make66** [mariomatzulla/cal#3]
Classes/Hooks/TceMainProcessdatamap.php:98 $notificationService->controller->getDateTimeObject = new \TYPO3\CMS\Cal\Model\CalDate( $event ['start_date'] . '000000' );
#1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Creating default object from empty value in /home/thescottishgavel.com/typo3conf/ext/cal/Classes/Hooks/TceMainProcessdatamap.php line 98

Das kommt, wenn ich eine Category zuweise und den Event speichern will. Die Category wird übernommen.

**Comment by mariomatzulla** [comment]
hilft commit 230aea4f09ae4117b971d2888a708e7301784157?

**Comment by Make66** [comment]
solves the issue.
