### ISSUE TITLE
Recurrence View in backend broken

### ISSUE THREAD

**Issue by Make66** [mariomatzulla/cal#6]
[CalBeRecurrenceView.pdf](https://github.com/mariomatzulla/cal/files/5251535/CalBeRecurrenceView.pdf)

**Comment by mariomatzulla** [comment]
committed with 064654030be8cd9b16937caeeee061c7cca169f5

**Comment by Make66** [comment]
Hallo Mario,

kann Deinen Commit nicht finden, da ist nichts vom 09.Oktober, wenn ich auf den Link "7 commits" klicke:


Habe das ZIP auf meinen Server hochgeladen, ausgepackt, umbenannt, Rechte korrigiert, PHP Cache gelöscht, Autoloaderklassen neu erstellt. Jetzt sieht das Recurrence-Backend genauso aus wie mit Fehler.

Was habe ich falsch gemacht?
Wie könnte ich den Vorgang vereinfachen?

Danke...

Mit freundlichen Grüßen,

Martin Keller
Taketool GmbH
+49 1726735396

**Comment by mariomatzulla** [comment]
Sorry, vergessen zu pushen
